### ISSUE TITLE
Add 'station' field to site-year and collector tables

### ISSUE THREAD

**Issue by TobieSurette** [TobieSurette/lobster-collectors#12]
Station number indicates the specific location where the collectors were placed. Movement to a new location should be indicated by an increment to the station number at that site.

For instance, Murray Harbour was moved in 2014, 2015 and 2016 by 500 meters. These are three different sampling locations. Station number should reflect this.

**Comment by degagnon2018** [comment]
Many sites have moved varying number of meters from year to year, we should determine a cut-off point when it becomes a different station. For the moment, I have different stations for collectos at deeper depths.

**Comment by degagnon2018** [comment]
The collectors deployed at a greater depth at some of the sites (Fortune, Nine Mile Creek) have been assigned with a station flag of 2. All others have a station 1 flag. Because collectors have GPS coordinates, we do not need to assign a station flag to site that may have moved by 500 meters.
