### ISSUE TITLE
Replace file paths in programs with http links to github files: read.collector, format.biological, etc...

### ISSUE THREAD

**Issue by TobieSurette** [TobieSurette/lobster-collectors#2]

**Comment by degagnon2018** [comment]
J'ai fait les changes, la seule chose faudrais regarder c'est ou on devrais faire le write et si on devrais utiliser le Here package pour ça.

**Comment by TobieSurette** [comment]
Les writes devraient etre locaux, so je pense pas que c'est un probleme
